// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRJ_8JGmHwnhn5TIjwKGH-memGlqqSRc',
    appId: '1:373058330074:web:f7f61259600187267474e3',
    messagingSenderId: '373058330074',
    projectId: 'furniture-sales-pred',
    authDomain: 'furniture-sales-pred.firebaseapp.com',
    storageBucket: 'furniture-sales-pred.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSDZcoIAL3LSSokhBagbvejwkIBHrLmw',
    appId: '1:373058330074:android:210731994e32350f7474e3',
    messagingSenderId: '373058330074',
    projectId: 'furniture-sales-pred',
    storageBucket: 'furniture-sales-pred.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxMvDjuwg40ONoz9oESDgO7-cXLah2k7c',
    appId: '1:373058330074:ios:f386d2f5fe8021a47474e3',
    messagingSenderId: '373058330074',
    projectId: 'furniture-sales-pred',
    storageBucket: 'furniture-sales-pred.firebasestorage.app',
    iosBundleId: 'com.example.furniturePred',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxMvDjuwg40ONoz9oESDgO7-cXLah2k7c',
    appId: '1:373058330074:ios:f386d2f5fe8021a47474e3',
    messagingSenderId: '373058330074',
    projectId: 'furniture-sales-pred',
    storageBucket: 'furniture-sales-pred.firebasestorage.app',
    iosBundleId: 'com.example.furniturePred',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoRJ_8JGmHwnhn5TIjwKGH-memGlqqSRc',
    appId: '1:373058330074:web:5e98bdb23bc0ba2a7474e3',
    messagingSenderId: '373058330074',
    projectId: 'furniture-sales-pred',
    authDomain: 'furniture-sales-pred.firebaseapp.com',
    storageBucket: 'furniture-sales-pred.firebasestorage.app',
  );
}
